# This workflow will build a Java project with Gradle across multiple operating systems
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:
    # Define the OS matrix for running the build on multiple operating systems
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v2

      # Set up JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Grant execute permission for gradlew (only needed for Unix-like systems)
      - name: Grant execute permission for gradlew
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      # Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: khdiv/java-app
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish:
    # Define that this job depends on the build-java job
    needs: build-java
    runs-on: ubuntu-latest
    
    steps:
      # Dummy step to ensure the job has at least one step and the workflow is valid
      - name: Dummy step
        run: echo "This is a dummy step to keep the publish job valid"


